### ISSUE TITLE
Query tip message will crash if there is no such tip

### ISSUE THREAD

**Issue by KunoSayo** [BAKAOLC/Ritsukage-Core#52]
**操作平台**  

QQ
**bug描述**  

+tipremove \<NoSuchTipId>

https://github.com/BAKAOLC/Ritsukage-Core/blob/8daf0492fa7536c8a6a76987336cc58041ffc8f8/Ritsukage-Core/Library/Service/TipMessageService.cs#LL30C1-L58C10

```C#

        public static async Task<T> GetAsync<T>(Expression<Func<T, bool>> predicate) where T : new()
            => (await Where(predicate)).First();
```
There is no first element and then crashed.

**如何复现**  

+tipremove \<NoSuchTipId>

**错误截图或日志**  

```log
[6/5/2023 8:42:42 PM][DEBUG][Commands]Parser: +tipremove 6
[6/5/2023 8:42:42 PM][DEBUG][Commands]Arguments:
   1| "6"
[6/5/2023 8:42:42 PM][DEBUG][Commands]found 1 command(s) for tipremove
[6/5/2023 8:42:42 PM][DEBUG][Commands]>> Start the precondition check for Void TipRemove(Ritsukage.QQ.SoraMessage, Int32)
[6/5/2023 8:42:42 PM][DEBUG][Commands]  >> Precondition: [<Can work in: Group>] √ Passed.
[6/5/2023 8:42:42 PM][DEBUG][Commands]>> Precondition check passed.
[6/5/2023 8:42:42 PM][DEBUG][Commands]Try to parse parameters for Void TipRemove(Ritsukage.QQ.SoraMessage, Int32).
[6/5/2023 8:42:42 PM][DEBUG][Commands]Invoke Void TipRemove(Ritsukage.QQ.SoraMessage, Int32).
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at lambda_method4999(Closure)
   at Ritsukage.Library.Data.Database.GetAsync[T](Expression`1 predicate) in /home/ubuntu/project/Ritsukage-Core/Ritsukage-Core/Library/Data/Database.cs:line 117
   at Ritsukage.Library.Service.TipMessageService.GetTipMessageById(Int32 id) in /home/ubuntu/project/Ritsukage-Core/Ritsukage-Core/Library/Service/TipMessageService.cs:line 34
   at Ritsukage.QQ.Commands.TipMessage.TipRemove(SoraMessage e, Int32 id) in /home/ubuntu/project/Ritsukage-Core/Ritsukage-Core/QQ/Commands/TipMessage.cs:line 109
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
**补充信息**  
Running on `Linux VM-4-11-ubuntu 5.4.0-150-generic #167-Ubuntu SMP Mon May 15 17:35:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

看返回类型不是Nullable我没敢动😭

![{KK{ }7B6ZB {}UA@T()XD6](https://github.com/BAKAOLC/Ritsukage-Core/assets/32478104/965a0d45-0a9f-4691-86d8-935f7fca0eab)

模板注释和模板内容看的眼花缭乱 😨 
~~其他的小issue合并一起提提算了~~
* https://github.com/BAKAOLC/Ritsukage-Core/blob/8daf0492fa7536c8a6a76987336cc58041ffc8f8/Acquisition/Acquisition/Aria/AriaHttpAcquisition.cs#L18
  次次检查exe文件，可能会由于上层循环重复下载，导致硬盘IO爆炸
* * ~~下载代码锁死windows平台，哪怕是把exe替换成了对应平台文件~~
* 每次Crash的时候导致Ubuntu控制台没有回显，直到输入回车（未知原因）

**Comment by BAKAOLC** [comment]
下载代码后续可能准备拿HttpClient重写一个简单多线程下载
另外直接挂宏区分系统走不同管道逻辑不就好了

**Comment by BAKAOLC** [comment]
至于CheckResources，按理说那里只有一次启动前检查，你要不再确认一下

**Comment by KunoSayo** [comment]
那可能算是我的问题。之前跑在ubuntu上，下载文件crash了，然后进程光速重启，并由于某种原因无限读不知道哪的文件。（也可能是其他地方死循环了）具体点是服务器崩了好几次连不上ssh，外部看资源监视器硬盘IO几百MB/s停不下来，不确定是啥原因

<hr>
dotnet run和build的虚拟内存是几百G（服务器内存就2G 硬盘40G），不知道和这个有没有关系😓
<hr>
client为 go-cqhttp

**Comment by BAKAOLC** [comment]
那就是说明在无限crash导致循环，没有在ubuntu上运行过所以我不知道，为什么你不在测试环境外面套一个中断器
